### ISSUE TITLE
⚠ HTTPS Certificate expired

### ISSUE THREAD

**Issue by fractalbach** [OpenCourseAPI/OwlAPI#64]
![image](https://user-images.githubusercontent.com/32124562/42208496-2456e634-7e61-11e8-9b75-7675e9a5e98d.png)

![image](https://user-images.githubusercontent.com/32124562/42208591-65a701c8-7e61-11e8-8a51-1c305abd9b0d.png)

**Comment by phi-line** [comment]
Okay I'll get it updated. It should auto-update but I suppose the service did not retrigger.

**Comment by phi-line** [comment]
Should be renewed. Verify [here](https://floof.li/)
