### ISSUE TITLE
Querying with course modifiers

### ISSUE THREAD

**Issue by madhavarshney** [OpenCourseAPI/OwlAPI#75]
**UPDATE**: Our course key parsing logic is indeed broken. Fixing that will fix this issue as well.

Querying with course modifiers included does not currently work. Searching for courses with certain modifiers, such as `H` for Honors, is a common use case and should be accounted for. A spike to investigate which modifiers should be queryable and which shouldn't, along with how feasible it is to do with or without creating special cases, is necessary.

For example, the ENGL 1BH only shows up at [/fh/single?dept=ENGL&course=1B](https://opencourse.dev/fh/single?dept=ENGL&course=1B) but not at [/fh/single?dept=ENGL&course=1BH](https://opencourse.dev/fh/single?dept=ENGL&course=1BH).

```json
[
  {
    "CRN": "21132",
    "campus": "FH",
    "course": "ENGL F01BH1HW",
    "days": "TBA",
    "desc": "HONORS COMP,CRITICAL READ & TH",
    "end": "12/11/2020",
    "instructor": "Armerding",
    "room": "ONLINE",
    "seats": "29",
    "start": "09/21/2020",
    "status": "Open",
    "time": "TBA",
    "units": "5.00",
    "wait_cap": "25",
    "wait_seats": "25"
  }
]
```

**Comment by PandawanFr** [comment]
I think this is related, but it also seems like classes that have more than one letter in their name suffer from the same issue. De Anza has `CIS 21JA` but the API returns it as `21J`. In this case, the A is not a modifier; there is no class named `21J` only `21JA`.

**Comment by madhavarshney** [comment]
Yes, I have noticed this as well. Some H courses show up while others don't. It seems that our section parsing logic is broken.

**Comment by PandawanFr** [comment]
I was thinking of contributing to the project but I'm not sure if it's worth it. There seems to be a big PR opened from two years ago and it hasn't been added in. Now I don't know all the context, but I wouldn't want to submit one only for the same thing to happen.

**Comment by madhavarshney** [comment]
Actually, that PR was WIP and @TryExceptElse didn't get a chance to finish it. There is separate work going on to extract the useful bits from that PR and merge them back into master. That's why that PR has been open for a while 😄 .
